{
 "title": "Apex Legends",
 "description": "Dashboard for the Apex Legends",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({scrape_job=\"apex-legends-exporter\"},player_name)"
    }
   },
   {
    "name": "map_image_url",
    "label": "map_image_url",
    "query": {
     "query": "label_values(apex_current_map_image_info{image=\"$map_image_url\"},image)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Player Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Player",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_identifier_info{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ player }}"
    }
   ]
  },
  {
   "title": "Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_level{job=\"apex-legends-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Legend Kills",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_legend_kills{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ legend_name }}"
    }
   ]
  },
  {
   "title": "Next Map",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_next_map_info{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ map_name }}"
    }
   ]
  },
  {
   "title": "Start",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_next_map_start_total{job=\"apex-legends-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Map",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_current_map_info{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ map_name }}"
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_current_map_remaining_total{job=\"apex-legends-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_platform_info{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "To Next Lvl.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_next_level_percentage{job=\"apex-legends-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Kills",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_kills_total{job=\"apex-legends-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Legend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_selected_legend_info{job=\"apex-legends-exporter\"}",
     "legendFormat": "{{ legend_name }}"
    }
   ]
  },
  {
   "title": "K/D",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_player_kill_death_ratio{job=\"apex-legends-exporter\"}"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_deaths\", player_name=\"$player\"}"
    }
   ]
  },
  {
   "title": "Total Damage Done",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csgo_stats_metric{name=\"total_damage_done\", player_name=\"$player\"}"
    }
   ]
  }
 ]
}